version: "3.9"
# needs standalone:php, phpmyadmin 
# modules: do they stay in volumes?
# updating workflow
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8082:80
    container_name: wordpress
    volumes:
      - wp_test2:/var/www/html
    environment: 
      - WORDPRESS_DB_HOST=${WP_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USR}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PW}
      - WORDPRESS_DB_NAME=${MYSQL_DB}
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: mysqldb
    volumes:
      - wp_test2_mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DR_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USR}
      - MYSQL_PASSWORD=${MYSQL_PW}
volumes:
  wp_test2:
  wp_test2_mysqldb: